export const INDIA_CITY_OPTIONS = [
  'Mumbai, Maharashtra',
  'Delhi, Delhi',
  'Bengaluru, Karnataka',
  'Hyderabad, Telangana',
  'Chennai, Tamil Nadu',
  'Kolkata, West Bengal',
  'Pune, Maharashtra',
  'Ahmedabad, Gujarat',
  'Jaipur, Rajasthan',
  'Surat, Gujarat',
  'Lucknow, Uttar Pradesh',
  'Kanpur, Uttar Pradesh',
  'Nagpur, Maharashtra',
  'Indore, Madhya Pradesh',
  'Bhopal, Madhya Pradesh',
  'Patna, Bihar',
  'Vadodara, Gujarat',
  'Ludhiana, Punjab',
  'Agra, Uttar Pradesh',
  'Nashik, Maharashtra',
  'Faridabad, Haryana',
  'Meerut, Uttar Pradesh',
  'Rajkot, Gujarat',
  'Varanasi, Uttar Pradesh',
  'Srinagar, Jammu and Kashmir',
  'Aurangabad, Maharashtra',
  'Dhanbad, Jharkhand',
  'Amritsar, Punjab',
  'Navi Mumbai, Maharashtra',
  'Allahabad, Uttar Pradesh',
  'Ranchi, Jharkhand',
  'Howrah, West Bengal',
  'Coimbatore, Tamil Nadu',
  'Jabalpur, Madhya Pradesh',
  'Gwalior, Madhya Pradesh',
  'Vijayawada, Andhra Pradesh',
  'Jodhpur, Rajasthan',
  'Madurai, Tamil Nadu',
  'Raipur, Chhattisgarh',
  'Kota, Rajasthan',
  'Guwahati, Assam',
  'Chandigarh, Chandigarh',
  'Solapur, Maharashtra',
  'Hubballi, Karnataka',
  'Bareilly, Uttar Pradesh',
  'Moradabad, Uttar Pradesh',
  'Mysuru, Karnataka',
  'Gurugram, Haryana',
  'Aligarh, Uttar Pradesh',
  'Jalandhar, Punjab',
  'Tiruchirappalli, Tamil Nadu',
  'Bhubaneswar, Odisha',
  'Salem, Tamil Nadu',
  'Warangal, Telangana',
  'Guntur, Andhra Pradesh',
  'Bhiwandi, Maharashtra',
  'Noida, Uttar Pradesh',
  'Ghaziabad, Uttar Pradesh',
  'Thiruvananthapuram, Kerala',
  'Kochi, Kerala',
  'Kozhikode, Kerala',
  'Thrissur, Kerala',
  'Malappuram, Kerala',
  'Kollam, Kerala',
  'Ujjain, Madhya Pradesh',
  'Dehradun, Uttarakhand',
  'Saharanpur, Uttar Pradesh',
  'Jamshedpur, Jharkhand',
  'Asansol, West Bengal',
  'Cuttack, Odisha',
  'Ajmer, Rajasthan',
  'Mangaluru, Karnataka',
  'Belagavi, Karnataka',
  'Nellore, Andhra Pradesh',
  'Tirupati, Andhra Pradesh',
  'Kurnool, Andhra Pradesh',
  'Anantapur, Andhra Pradesh',
  'Nizamabad, Telangana',
  'Karimnagar, Telangana',
  'Khammam, Telangana',
  'Bhavnagar, Gujarat',
  'Jamnagar, Gujarat',
  'Anand, Gujarat',
  'Gandhinagar, Gujarat',
  'Vapi, Gujarat',
  'Bhuj, Gujarat',
  'Siliguri, West Bengal',
  'Durgapur, West Bengal',
  'Kharagpur, West Bengal',
  'Haldia, West Bengal',
  'Bokaro, Jharkhand',
  'Hazaribagh, Jharkhand',
  'Dumka, Jharkhand',
  'Bilaspur, Chhattisgarh',
  'Korba, Chhattisgarh',
  'Durg, Chhattisgarh',
  'Bhilai, Chhattisgarh',
  'Ambikapur, Chhattisgarh',
  'Amravati, Maharashtra',
  'Akola, Maharashtra',
  'Kolhapur, Maharashtra',
  'Sangli, Maharashtra',
  'Jalgaon, Maharashtra',
  'Nanded, Maharashtra',
  'Latur, Maharashtra',
  'Satara, Maharashtra',
  'Panaji, Goa',
  'Margao, Goa',
  'Ponda, Goa',
  'Imphal, Manipur',
  'Aizawl, Mizoram',
  'Shillong, Meghalaya',
  'Agartala, Tripura',
  'Kohima, Nagaland',
  'Dimapur, Nagaland',
  'Itanagar, Arunachal Pradesh',
  'Gangtok, Sikkim',
  'Port Blair, Andaman and Nicobar Islands',
  'Puducherry, Puducherry',
  'Kakinada, Andhra Pradesh',
  'Rajahmundry, Andhra Pradesh',
  'Eluru, Andhra Pradesh',
  'Kadapa, Andhra Pradesh',
  'Vizianagaram, Andhra Pradesh',
  'Srikakulam, Andhra Pradesh',
  'Rohtak, Haryana',
  'Hisar, Haryana',
  'Panipat, Haryana',
  'Karnal, Haryana',
  'Ambala, Haryana',
  'Yamunanagar, Haryana',
  'Sonipat, Haryana',
  'Rewari, Haryana',
  'Kurukshetra, Haryana',
  'Bhiwani, Haryana',
  'Narnaul, Haryana',
  'Shimla, Himachal Pradesh',
  'Mandi, Himachal Pradesh',
  'Solan, Himachal Pradesh',
  'Dharamshala, Himachal Pradesh',
  'Hamirpur, Himachal Pradesh',
  'Jammu, Jammu and Kashmir',
  'Udhampur, Jammu and Kashmir',
  'Anantnag, Jammu and Kashmir',
  'Baramulla, Jammu and Kashmir',
  'Leh, Ladakh',
  'Kargil, Ladakh',
  'Gaya, Bihar',
  'Muzaffarpur, Bihar',
  'Bhagalpur, Bihar',
  'Purnia, Bihar',
  'Darbhanga, Bihar',
  'Arrah, Bihar',
  'Begusarai, Bihar',
  'Munger, Bihar',
  'Sasaram, Bihar',
  'Dibrugarh, Assam',
  'Jorhat, Assam',
  'Silchar, Assam',
  'Tezpur, Assam',
  'Tinsukia, Assam',
  'Nagaon, Assam',
  'Bongaigaon, Assam',
  'Sambalpur, Odisha',
  'Rourkela, Odisha',
  'Berhampur, Odisha',
  'Balasore, Odisha',
  'Puri, Odisha',
  'Kendujhar, Odisha',
  'Kolkata Suburbs, West Bengal',
  'Alwar, Rajasthan',
  'Bikaner, Rajasthan',
  'Udaipur, Rajasthan',
  'Bhilwara, Rajasthan',
  'Sikar, Rajasthan',
  'Pali, Rajasthan',
  'Bharatpur, Rajasthan',
  'Tonk, Rajasthan',
  'Jhunjhunu, Rajasthan',
  'Sagar, Madhya Pradesh',
  'Rewa, Madhya Pradesh',
  'Ratlam, Madhya Pradesh',
  'Dewas, Madhya Pradesh',
  'Katni, Madhya Pradesh',
  'Chhindwara, Madhya Pradesh',
  'Khandwa, Madhya Pradesh',
  'Shivpuri, Madhya Pradesh',
  'Mathura, Uttar Pradesh',
  'Aligarh, Uttar Pradesh',
  'Firozabad, Uttar Pradesh',
  'Jhansi, Uttar Pradesh',
  'Shahjahanpur, Uttar Pradesh',
  'Ayodhya, Uttar Pradesh',
  'Gorakhpur, Uttar Pradesh',
  'Noida Extension, Uttar Pradesh',
  'Prayagraj, Uttar Pradesh',
  'Muzaffarnagar, Uttar Pradesh',
  'Haridwar, Uttarakhand',
  'Roorkee, Uttarakhand',
  'Haldwani, Uttarakhand',
  'Rudrapur, Uttarakhand',
  'Nainital, Uttarakhand',
  'Palakkad, Kerala',
  'Kannur, Kerala',
  'Kottayam, Kerala',
  'Alappuzha, Kerala',
  'Pathanamthitta, Kerala',
  'Tumakuru, Karnataka',
  'Davanagere, Karnataka',
  'Ballari, Karnataka',
  'Shivamogga, Karnataka',
  'Vijayapura, Karnataka',
  'Udupi, Karnataka',
  'Hassan, Karnataka',
  'Bidar, Karnataka',
  'Roura, Odisha'
];
